boot.o: boot.S multiboot.h x86_desc.h types.h
interrupt_linkage.o: interrupt_linkage.S interrupt_linkage.h
x86_desc.o: x86_desc.S x86_desc.h types.h
exception.o: exception.c lib.h types.h exception.h
filesys.o: filesys.c lib.h types.h filesys.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c lib.h types.h x86_desc.h idt.h exception.h \
  interrupt_linkage.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h rtc.h keyboard.h paging.h
keyboard.o: keyboard.c keyboard.h lib.h types.h i8259.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h lib.h
rtc.o: rtc.c rtc.h types.h lib.h i8259.h tests.h
terminal.o: terminal.c terminal.h types.h keyboard.h lib.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h i8259.h idt.h rtc.h \
  terminal.h
